/**
 * ============================================================
 * OFL • HQ — SITE CONFIGURATION
 * ============================================================
 * Generated by Site Admin on April 10, 2026
 *
 * HOW TO USE:
 *   1. Save this file as config.js in your website folder
 *   2. Make sure index.html loads it: <script src="config.js"></script>
 *   3. Reload the website — your changes appear automatically
 * ============================================================
 */

const SITE_CONFIG = {
  "firmName": "OFL • HQ",
  "tagline": "Osborne Fantasy League",
  "preloaderTagline": "Alabama • Tennessee • Georgia",
  "pageHeaders": {
    "about": {
      "label": "About Us",
      "title": "Meet Our Team",
      "subtitle": ""
    },
    "contact": {
      "label": "Smash Us"
    }
  },
  "attorneyName": "Amy Michelle Osborne",
  "attorneyDegree": "J.D., Birmingham School of Law",
  "attorneyCredentials": [
    "AL State Bar",
    "J.D., Birmingham Law",
    "ABA Member",
    "Super Lawyers",
    "AAAA Member"
  ],
  "aboutBio1": "For over 20 years, Amy Osborne has dedicated her practice exclusively to adoption and family formation law in Alabama. She has helped more than 500 families complete adoptions — from straightforward stepparent cases to complex interstate and contested matters.",
  "aboutBio2": "Amy grew up watching her own family navigate a difficult adoption, which gave her a deeply personal understanding of what families go through. She founded Osborne Law Firm, LLC with a single mission: to make adoption less daunting and more accessible for every family, regardless of their background or circumstances. She is a member of the Alabama Bar Association, the American Academy of Adoption Attorneys (AAAA), and has been recognized as a Super Lawyer in Alabama Family Law for eight consecutive years. She is admitted to practice in all Alabama courts and regularly handles cases in Jefferson, Shelby, St. Clair, and Cullman counties. When she's not advocating for families in court, Amy volunteers with the Alabama Foster Care Association and speaks at community workshops on adoption awareness.",
  "attorneyPhoto": "images/ladybug.png",
  "attorneys": [
    {
      "name": "Amy Michelle Osborne",
      "degree": "J.D., Birmingham School of Law",
      "photo": "images/ladybug.png",
      "credentials": [
        "AL State Bar",
        "J.D., Birmingham Law",
        "ABA Member",
        "Super Lawyers",
        "AAAA Member"
      ],
      "bio1": "For over 20 years, Amy Osborne has dedicated her practice exclusively to adoption and family formation law in Alabama. She has helped more than 500 families complete adoptions — from straightforward stepparent cases to complex interstate and contested matters.",
      "bio2": "Amy grew up watching her own family navigate a difficult adoption, which gave her a deeply personal understanding of what families go through. She founded Osborne Law Firm, LLC with a single mission: to make adoption less daunting and more accessible for every family, regardless of their background or circumstances. She is a member of the Alabama Bar Association, the American Academy of Adoption Attorneys (AAAA), and has been recognized as a Super Lawyer in Alabama Family Law for eight consecutive years. She is admitted to practice in all Alabama courts and regularly handles cases in Jefferson, Shelby, St. Clair, and Cullman counties. When she's not advocating for families in court, Amy volunteers with the Alabama Foster Care Association and speaks at community workshops on adoption awareness."
    }
  ],
  "phone": "(555) 448-8787 // HIT-USUP",
  "phoneRaw": "+15554488787",
  "fax": "(555) 329-1846 // FAX-PAIN",
  "email": "ofloperations@gmail.com",
  "address": "54321 Winners Lane",
  "city": "Champions",
  "state": "USA",
  "stateAbbr": "US",
  "zip": "11111",
  "hours": [
    {
      "days": "Monday – Friday",
      "hours": "Closed"
    },
    {
      "days": "Saturday – Sunday",
      "hours": "Open 8am - 10pm EDT"
    }
  ],
  "socialLinks": [
    {
      "platform": "facebook",
      "url": "Facebook.com"
    },
    {
      "platform": "instagram",
      "url": "Google.com"
    },
    {
      "platform": "linkedin",
      "url": "Google.com"
    },
    {
      "platform": "x",
      "url": "Google.com"
    },
    {
      "platform": "youtube",
      "url": "Google.com"
    },
    {
      "platform": "tiktok",
      "url": "Google.com"
    },
    {
      "platform": "custom",
      "url": "https://auspider98.github.io/OFL/index.html"
    }
  ],
  "stats": [
    {
      "num": "20+",
      "label": "Years of Battles"
    },
    {
      "num": "BRC",
      "label": "Blue Ribbon Cup"
    },
    {
      "num": "★6",
      "label": "Rating"
    },
    {
      "num": "OFL",
      "label": "Osborne Football Club"
    },
    {
      "num": "15+",
      "label": "Warrors"
    }
  ],
  "colors": {
    "navy": "#000000",
    "navyLight": "#292929",
    "gold": "#e6c875",
    "goldLight": "#d2ae4b",
    "goldPale": "#faf6ec",
    "warmWhite": "#fffdf9",
    "cream": "#f9f6f0",
    "chrome": "#000000"
  },
  "fontColors": {
    "heading": "#000000",
    "body": "#5c5a53",
    "onDark": "#ffffff",
    "onDarkMuted": "#f3f8fb"
  },
  "fontDisplay": "Raleway",
  "fontBody": "Assistant",
  "metaDescription": "Where Legends Are Made & Legacies Are Settled",
  "metaKeywords": "ofl osborne fantasy league ofc football club brc blue ribbon cup",
  "googleAnalyticsId": "",
  "formEndpoint": "",
  "pageTitles": {
    "home": "OFL Headquarters",
    "about": "About the Us",
    "contact": "Contact Us",
    "privacy": "Privacy Policy"
  },
  "heroBg": {
    "type": "video",
    "bgColor": "#0f2340",
    "imagePath": "images/hero-bkground-01.jpg",
    "imagePosition": "center center",
    "slides": [
      {
        "imagePath": "images/hero-bkground-01.jpg",
        "position": "center top"
      },
      {
        "imagePath": "images/hero-bkground-03.webp",
        "position": "center center"
      },
      {
        "imagePath": "images/hero-bkground-02.jpg",
        "position": "center top"
      },
      {
        "imagePath": "images/hero-bkground-04.jpg",
        "position": "center bottom"
      }
    ],
    "transition": "crossfade",
    "transitionSpeed": 2,
    "slideDuration": 10,
    "pauseOnHover": false,
    "showDots": true,
    "autoplay": true,
    "motionType": "zoom-out",
    "motionSpeed": 10,
    "overlayColor": "#000000",
    "overlayOpacity": 0.2,
    "videoMp4": "videos/hero-bkground-v01.mp4",
    "videoWebm": "",
    "videoFallback": "images/hero-bkground-01.jpg",
    "videoLoop": "crossfade",
    "videoHold": 4,
    "video2Mp4": "videos/hero-bkground-v02.mp4",
    "video2Webm": "",
    "videoFallback2": "",
    "videoClips": [
      {
        "mp4": "videos/hero-bkground-v00.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center right",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 0
      },
      {
        "mp4": "videos/hero-bkground-v01.mp4",
        "webm": "",
        "fallback": "images/hero-bkground-01.jpg",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 0
      },
      {
        "mp4": "videos/hero-bkground-v02.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center left",
        "playbackRate": 1.5,
        "startTime": 0,
        "playDuration": 0
      }
    ],
    "videoHoldEnabled": false,
    "videoTransSpeed": 2
  },
  "heroHeadline": "Where Legends Are Made & Legacies Are Settled",
  "heroSubline": "We provide an unbeatable fantasy sports experience unmatched anywhere. Our competitors are handpicked or raised from birth to be true warriors on the gridiron, hardwood, and online. If you're here because of an invitation, its great to see you again. If you're here looking around...scram...you're not worthy!",
  "heroTrustBullets": [
    "Parent Company of the OFL and BRC",
    "Tri-State Battleground Covering 4 Cities",
    "20+ Glorious Trophies Recognizing Fame or Failure",
    "20+ Warrior Records for High Horses",
    "20+ Years Trash Talking for the Mighty"
  ],
  "heroPrimaryLabel": "Smash Us",
  "heroPrimaryLinkType": "internal",
  "heroPrimaryLinkUrl": "contact",
  "heroSecondaryLabel": "OFL League Page",
  "heroSecondaryLinkType": "external",
  "heroSecondaryLinkUrl": "https://auspider98.github.io/OFL/index.html",
  "whyChooseUs": {
    "heading": "You Don't Choose Us...You are Chosen!",
    "subtext": "",
    "badgeNum": "20+",
    "badgeLabel": "Years",
    "bullets": [
      {
        "title": "Adoption-Only Focus",
        "desc": "We practice exclusively in adoption and family formation law, so you get deep expertise — not a generalist."
      },
      {
        "title": "Plain-Language Guidance",
        "desc": "We explain every step in clear, honest language — no legal jargon, no confusion."
      },
      {
        "title": "Responsive & Personal",
        "desc": "You'll always know where your case stands. We return calls and emails promptly."
      },
      {
        "title": "Local Court Knowledge",
        "desc": "Familiar with courts across Alabama, we know the local rules and judges that matter to your case."
      }
    ]
  },
  "contactHeadline": "Give us a shout and talk a little trash.",
  "contactSubline": "No obligation, no pressure — actually, shut up, sit down, and stop crying.",
  "contactFormHeading": "WHATCHUCOMPLAININBOUT",
  "contactFormIntro": "Fill out this form and get reverse karma within one business day to the satisfaction of the league office.",
  "contactPrivacyNote": "🔒 Your information is strictly not confidential and will be shared all over social media.",
  "contactForm": [
    {
      "type": "text",
      "label": "First Name",
      "placeholder": "Justin",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "text",
      "label": "Last Name",
      "placeholder": "Adequate",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "email",
      "label": "Email Address",
      "placeholder": "justin@adequate .com",
      "required": true,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "phone",
      "label": "Phone Number",
      "placeholder": "(555) 873-5377",
      "required": false,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "select",
      "label": "What's Up?",
      "placeholder": "[ Select One ]",
      "required": false,
      "halfWidth": false,
      "options": [
        "What Is This",
        "Membership",
        "Contact Me",
        "Not Sure / General Question"
      ]
    },
    {
      "type": "textarea",
      "label": "Why Are You Bothering Us",
      "placeholder": "Share as much or as little as you'd like...we won't read it.",
      "required": false,
      "halfWidth": false,
      "options": []
    }
  ],
  "services": [
    {
      "icon": "👫",
      "title": "Stepparent Adoption",
      "desc": "Legally adopt your stepchild and become their parent in every sense of the word — including inheritance and legal rights.",
      "full": "Stepparent adoption is one of the most common types of adoption in Alabama. If your spouse has a child from a previous relationship, you may petition the court to legally adopt that child. We handle consent issues, parental rights terminations when needed, and home study waivers."
    },
    {
      "icon": "👴",
      "title": "Relative / Kinship Adoption",
      "desc": "Grandparents, aunts, uncles, or other relatives can adopt to provide permanency for a child who cannot remain with their parents.",
      "full": "Kinship adoption allows extended family members to provide a safe, stable home when a child's parents are unable to care for them. Tennessee courts look favorably on keeping children within their family network. We guide relatives through every step, including the home study process."
    },
    {
      "icon": "🍼",
      "title": "Private Placement Adoption",
      "desc": "Work directly with a birth mother through a private, licensed process with full legal protection for all parties.",
      "full": "In a private placement adoption, an expectant mother chooses the adoptive family directly. We represent adoptive families and work with birth parent counsel to ensure the process is legally sound, ethical, and protected under Alabama law."
    },
    {
      "icon": "🏢",
      "title": "Agency Adoption",
      "desc": "Adopt through a licensed Alabama adoption agency, with expert guidance to navigate the agency's requirements and the court process.",
      "full": "If you're working with a licensed adoption agency, you'll still need an adoption attorney to finalize the adoption in court. We handle the legal finalization and work cooperatively with your chosen agency throughout the process."
    },
    {
      "icon": "🏛️",
      "title": "Adult Adoption",
      "desc": "Formalize a meaningful parent-child bond that already exists between an adult and a caregiver — with full legal recognition.",
      "full": "Adult adoption in Alabama allows someone 18 or older to be legally adopted. This is often used to formalize a long-standing parental relationship, inheritance planning, or to honor a meaningful family bond. The process is generally simpler than minor adoptions."
    },
    {
      "icon": "🌎",
      "title": "Interstate Adoption (ICPC)",
      "desc": "Adopting a child from another state? We manage the complex Interstate Compact on Placement of Children requirements.",
      "full": "The Interstate Compact on the Placement of Children (ICPC) governs adoptions across state lines. Both states must approve the placement before the child can travel. We coordinate with authorities in both states to keep your adoption on track."
    },
    {
      "icon": "⚔️",
      "title": "Contested Adoption",
      "desc": "When a birth parent contests an adoption, you need an experienced litigator in your corner. We're not afraid of courtrooms.",
      "full": "Contested adoptions arise when a birth parent disputes the termination of their parental rights. These cases require skilled legal strategy and courtroom advocacy. Attorney Harlow has extensive experience litigating contested adoptions in Tennessee courts."
    },
    {
      "icon": "📋",
      "title": "Termination of Parental Rights",
      "desc": "A necessary legal step in many adoptions — we handle voluntary and involuntary TPR proceedings with care.",
      "full": "Before most adoptions can be finalized, the birth parent's parental rights must be legally terminated. This can be voluntary (the parent consents) or involuntary (the court orders termination). We handle both types and ensure all due process requirements are met."
    },
    {
      "icon": "🌈",
      "title": "Same-Sex & Second-Parent Adoption",
      "desc": "We proudly serve LGBTQ+ families seeking to ensure both parents have full legal rights to their child.",
      "full": "We proudly represent LGBTQ+ families navigating stepparent, second-parent, and joint adoptions. Alabama law recognizes same-sex couples' rights to adopt, and we ensure both parents receive full legal protection and parental recognition."
    }
  ],
  "faqs": [
    {
      "q": "How long does a stepparent adoption take in Tennessee?",
      "a": "Most uncontested stepparent adoptions in Tennessee take between 3 and 6 months from filing to finalization. The timeline depends on court availability, whether the other parent's rights need to be terminated, and how quickly the required documents are gathered."
    },
    {
      "q": "Do I need a home study for a stepparent adoption?",
      "a": "Not always. Tennessee law allows the court to waive the home study requirement in stepparent adoptions when the petitioner has lived with the child for a sufficient period and the circumstances warrant it. We'll advise you based on your specific situation."
    },
    {
      "q": "What if the birth parent won't consent to adoption?",
      "a": "If a birth parent refuses to consent, the court can still terminate their parental rights in certain circumstances — such as abandonment, failure to pay support, or unfitness. These are contested adoptions, which require a court hearing. We have extensive experience in contested adoption cases."
    },
    {
      "q": "How much does adoption cost in Tennessee?",
      "a": "Costs vary significantly by adoption type. Stepparent and relative adoptions are typically the most affordable ($1,500–$4,000 in attorney fees). Private placement adoptions may involve additional costs including birth parent expenses, agency fees, and court costs. We provide transparent fee estimates in your consultation."
    },
    {
      "q": "Can same-sex couples adopt in Tennessee?",
      "a": "Yes. Tennessee recognizes the right of same-sex couples to adopt. We proudly serve LGBTQ+ families in all types of adoption, including stepparent, second-parent, and agency adoptions."
    },
    {
      "q": "What is the Interstate Compact on the Placement of Children (ICPC)?",
      "a": "The ICPC is a legal agreement between all U.S. states that governs how children can be placed for adoption across state lines. Before a child placed for adoption in one state can be brought to another state, both states must approve the placement. This adds time and paperwork — but we handle all of it."
    },
    {
      "q": "Do I need an attorney for adoption in Tennessee?",
      "a": "Yes. Tennessee law requires that all adoptions be finalized in court, and you must have a licensed Tennessee attorney represent you. Attempting to complete an adoption without an attorney significantly increases the risk of errors that can delay or derail the process."
    },
    {
      "q": "What rights does an adopted child have?",
      "a": "An adopted child has the same legal rights as a biological child — including inheritance rights, the right to be covered by a parent's insurance, and access to Social Security benefits. The child will receive a new birth certificate listing the adoptive parent(s)."
    }
  ],
  "testimonials": [
    {
      "name": "Frank Goodson",
      "initials": "FT",
      "stars": "1",
      "text": "I submitted a request for membership and now I'm subscribed to Women's World magazine and keep getting text messages from a doctors office asking me to confirm my appointment for a colonoscopy?!",
      "meta": "WTH • Richmond, VA"
    },
    {
      "name": "Tracy Billings",
      "initials": "TB",
      "stars": "1",
      "text": "Why did this page show up in my search for body piercings?",
      "meta": "Search Error • Grand Rapids, MI"
    },
    {
      "name": "Jim Friedman",
      "initials": "JF",
      "stars": "1",
      "text": "My employee keeps bossing me around and bosting about his OFL trophies and BRC records. I'd fire him for insubordination, but he's an incredible employee and the coolest guy I know. Because of your organization I feel so small.",
      "meta": "Unworthy • Southeastern US"
    }
  ],
  "blogPosts": [
    {
      "emoji": "📋",
      "tag": "Guide",
      "imagePath": "",
      "title": "Stepparent Adoption in Alabama: A Complete 2025 Guide",
      "excerpt": "Everything you need to know about legally adopting your stepchild in Alabama — requirements, timeline, costs, and common questions answered.",
      "date": "January 15, 2025",
      "readTime": "",
      "featured": false,
      "linkType": "none",
      "linkUrl": "",
      "ctaLabel": ""
    },
    {
      "emoji": "⚖️",
      "tag": "Legal Info",
      "imagePath": "",
      "title": "What Is Termination of Parental Rights and When Is It Required?",
      "excerpt": "Before most adoptions can be finalized, a birth parent's rights must be legally terminated. Learn what that means and how it works in Alabama courts.",
      "date": "December 8, 2024",
      "readTime": "",
      "featured": false,
      "linkType": "none",
      "linkUrl": "",
      "ctaLabel": ""
    },
    {
      "emoji": "🌎",
      "tag": "Interstate",
      "imagePath": "",
      "title": "Navigating the ICPC: Interstate Adoption Explained",
      "excerpt": "If you're adopting a child from another state, you'll encounter the ICPC. Here's what it is, how it works, and how we help you through it.",
      "date": "November 22, 2024",
      "readTime": "",
      "featured": false,
      "linkType": "none",
      "linkUrl": "",
      "ctaLabel": ""
    },
    {
      "emoji": "👴",
      "tag": "Kinship",
      "imagePath": "",
      "title": "Can Grandparents Adopt Their Grandchildren in Alabama?",
      "excerpt": "Yes — and it's often the best option for children who need stability within their family. Learn about relative adoption requirements and benefits.",
      "date": "October 14, 2024",
      "readTime": "",
      "featured": false,
      "linkType": "none",
      "linkUrl": "",
      "ctaLabel": ""
    },
    {
      "emoji": "🌈",
      "tag": "LGBTQ+",
      "imagePath": "",
      "title": "Same-Sex Adoption Rights in Alabama: What You Need to Know",
      "excerpt": "Alabama law recognizes same-sex couples' rights to adopt. Here's a plain-English overview of second-parent and joint adoptions for LGBTQ+ families.",
      "date": "September 5, 2024",
      "readTime": "",
      "featured": false,
      "linkType": "none",
      "linkUrl": "",
      "ctaLabel": ""
    },
    {
      "emoji": "💰",
      "tag": "Costs",
      "imagePath": "",
      "title": "How Much Does Adoption Cost in Alabama? A Realistic Breakdown",
      "excerpt": "Adoption costs vary widely by type. We break down typical attorney fees, court costs, home study fees, and other expenses so you can plan ahead.",
      "date": "August 20, 2024",
      "readTime": "",
      "featured": false,
      "linkType": "none",
      "linkUrl": "",
      "ctaLabel": ""
    }
  ],
  "processSteps": [
    {
      "num": 1,
      "title": "Free Consultation",
      "body": "We start with a free, no-obligation consultation — by phone or in person — to understand your situation. We'll explain which type of adoption applies to you, what to expect, and give you a realistic timeline and fee estimate. There's no pressure and no commitment required."
    },
    {
      "num": 2,
      "title": "Engagement & Case Review",
      "body": "Once you decide to move forward, we'll sign an engagement agreement and begin reviewing the details of your case. We gather the necessary information and documents, and advise you on any steps you need to take (such as locating a birth parent or obtaining records)."
    },
    {
      "num": 3,
      "title": "Preparing & Filing the Petition",
      "body": "We prepare all required legal documents, including the Petition for Adoption, and file them with the appropriate Alabama court. Filing fees apply and vary by county. We handle all court paperwork so you don't have to."
    },
    {
      "num": 4,
      "title": "Home Study (When Required)",
      "body": "Most adoptions in Alabama require a home study — an evaluation of your home and background conducted by a licensed agency or social worker. Some stepparent adoptions can waive this requirement. If a home study is required, we'll refer you to a reputable provider and guide you through what to expect."
    },
    {
      "num": 5,
      "title": "Consent & Termination of Parental Rights",
      "body": "Before finalization, the birth parent(s)' rights must be addressed — either through voluntary consent or court-ordered termination. We handle all aspects of this legally sensitive step, ensuring every document is executed correctly and that due process is followed."
    },
    {
      "num": 6,
      "title": "Court Hearing",
      "body": "Alabama adoption finalization requires a court hearing before a judge. We attend with you, present the case, and answer any questions the judge may have. These hearings are typically brief and celebratory! Many clients bring family members and take photos in the courtroom."
    },
    {
      "num": 7,
      "title": "Finalization & New Birth Certificate 🎉",
      "body": "The judge signs the Decree of Adoption — and your family is official! After finalization, we help you obtain a new birth certificate listing the adoptive parent(s) and, if applicable, apply for an updated Social Security record for the child."
    }
  ],
  "processRequirements": [
    {
      "q": "Residency Requirement",
      "a": "At least one party in the adoption must be a resident of Tennessee, or the child must have been in Tennessee for at least 6 months prior to filing."
    },
    {
      "q": "Home Study Requirement",
      "a": "Required in most adoptions unless waived by the court (common in stepparent adoptions). Must be conducted by a licensed Tennessee adoption agency or social worker."
    },
    {
      "q": "Background Check",
      "a": "All prospective adoptive parents must undergo state and federal criminal background checks. Certain prior convictions may disqualify a petitioner under Tennessee law."
    },
    {
      "q": "Consent of the Child",
      "a": "If the child being adopted is 14 years of age or older, they must consent to the adoption in writing."
    },
    {
      "q": "Waiting Period",
      "a": "For private placement and agency adoptions, a statutory waiting period applies before the final hearing. Stepparent adoptions generally have a shorter waiting period."
    }
  ],
  "ctaLabel": "Free Abuse",
  "pageToggles": {
    "about": true,
    "contact": true
  },
  "homeToggles": {
    "stats": true,
    "why": true,
    "testimonials": true
  },
  "customPages": [
    {
      "slug": "our-expertise",
      "navLabel": "Our Expertise",
      "emoji": "📄",
      "enabled": true,
      "sections": [
        {
          "type": "services",
          "label": "Practice Areas",
          "background": "alt",
          "heading": "Our Adoption Services",
          "subtitle": "Every adoption journey is unique. We offer comprehensive legal services across all types of adoption in Alabama.",
          "items": [
            {
              "icon": "👫",
              "title": "Stepparent Adoption",
              "desc": "Legally adopt your stepchild and become their parent in every sense of the word — including inheritance and legal rights.",
              "detail": "Stepparent adoption is one of the most common types of adoption in Alabama. If your spouse has a child from a previous relationship, you may petition the court to legally adopt that child. We handle consent issues, parental rights terminations when needed, and home study waivers.",
              "btnLabel": "",
              "btnLinkType": "none",
              "btnLinkUrl": "home"
            },
            {
              "icon": "👴",
              "title": "Relative / Kinship Adoption",
              "desc": "Grandparents, aunts, uncles, or other relatives can adopt to provide permanency for a child who cannot remain with their parents.",
              "detail": "Kinship adoption allows extended family members to provide a safe, stable home when a child's parents are unable to care for them. Tennessee courts look favorably on keeping children within their family network. We guide relatives through every step, including the home study process.",
              "btnLabel": "",
              "btnLinkType": "none",
              "btnLinkUrl": "home"
            },
            {
              "icon": "🍼",
              "title": "Private Placement Adoption",
              "desc": "Work directly with a birth mother through a private, licensed process with full legal protection for all parties.",
              "detail": "In a private placement adoption, an expectant mother chooses the adoptive family directly. We represent adoptive families and work with birth parent counsel to ensure the process is legally sound, ethical, and protected under Alabama law.",
              "btnLabel": "",
              "btnLinkType": "none",
              "btnLinkUrl": "home"
            },
            {
              "icon": "🏢",
              "title": "Agency Adoption",
              "desc": "Adopt through a licensed Alabama adoption agency, with expert guidance to navigate the agency's requirements and the court process",
              "detail": "If you're working with a licensed adoption agency, you'll still need an adoption attorney to finalize the adoption in court. We handle the legal finalization and work cooperatively with your chosen agency throughout the process.",
              "btnLabel": "",
              "btnLinkType": "none",
              "btnLinkUrl": "home"
            },
            {
              "icon": "🏛️",
              "title": "Adult Adoption",
              "desc": "Formalize a meaningful parent-child bond that already exists between an adult and a caregiver — with full legal recognition.",
              "detail": "Adult adoption in Alabama allows someone 18 or older to be legally adopted. This is often used to formalize a long-standing parental relationship, inheritance planning, or to honor a meaningful family bond. The process is generally simpler than minor adoptions.",
              "btnLabel": "",
              "btnLinkType": "none",
              "btnLinkUrl": "home"
            },
            {
              "icon": "🌎",
              "title": "Interstate Adoption (ICPC)",
              "desc": "Adopting a child from another state? We manage the complex Interstate Compact on Placement of Children requirements.",
              "detail": "The Interstate Compact on the Placement of Children (ICPC) governs adoptions across state lines. Both states must approve the placement before the child can travel. We coordinate with authorities in both states to keep your adoption on track.",
              "btnLabel": "",
              "btnLinkType": "none",
              "btnLinkUrl": "home"
            },
            {
              "icon": "⚔️",
              "title": "Contested Adoption",
              "desc": "When a birth parent contests an adoption, you need an experienced litigator in your corner. We're not afraid of courtrooms.",
              "detail": "Contested adoptions arise when a birth parent disputes the termination of their parental rights. These cases require skilled legal strategy and courtroom advocacy. Attorney Harlow has extensive experience litigating contested adoptions in Tennessee courts.",
              "btnLabel": "",
              "btnLinkType": "none",
              "btnLinkUrl": "home"
            },
            {
              "icon": "📋",
              "title": "Termination of Parental Rights",
              "desc": "A necessary legal step in many adoptions — we handle voluntary and involuntary TPR proceedings with care.",
              "detail": "Before most adoptions can be finalized, the birth parent's parental rights must be legally terminated. This can be voluntary (the parent consents) or involuntary (the court orders termination). We handle both types and ensure all due process requirements are met.",
              "btnLabel": "",
              "btnLinkType": "none",
              "btnLinkUrl": "home"
            },
            {
              "icon": "🌈",
              "title": "Same-Sex & Second-Parent Adoption",
              "desc": "We proudly serve LGBTQ+ families seeking to ensure both parents have full legal rights to their child",
              "detail": "We proudly represent LGBTQ+ families navigating stepparent, second-parent, and joint adoptions. Alabama law recognizes same-sex couples' rights to adopt, and we ensure both parents receive full legal protection and parental recognition.",
              "btnLabel": "",
              "btnLinkType": "none",
              "btnLinkUrl": "home"
            }
          ]
        }
      ]
    },
    {
      "slug": "our-process",
      "navLabel": "Our Process",
      "emoji": "📄",
      "enabled": true,
      "sections": [
        {
          "type": "steps",
          "label": "How It Works",
          "background": "dark",
          "heading": "The Adoption Process",
          "subtitle": "From your first call to finalization day — here's what to expect when you work with us.",
          "items": [
            {
              "title": "Free Consultation",
              "body": "We start with a free, no-obligation consultation — by phone or in person — to understand your situation. We'll explain which type of adoption applies to you, what to expect, and give you a realistic timeline and fee estimate. There's no pressure and no commitment required.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "title": "Engagement & Case Review",
              "body": "Once you decide to move forward, we'll sign an engagement agreement and begin reviewing the details of your case. We gather the necessary information and documents, and advise you on any steps you need to take (such as locating a birth parent or obtaining records).",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "title": "Preparing & Filing the Petition",
              "body": "We prepare all required legal documents, including the Petition for Adoption, and file them with the appropriate Alabama court. Filing fees apply and vary by county. We handle all court paperwork so you don't have to.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "title": "Home Study (When Required)",
              "body": "Most adoptions in Alabama require a home study — an evaluation of your home and background conducted by a licensed agency or social worker. Some stepparent adoptions can waive this requirement. If a home study is required, we'll refer you to a reputable provider and guide you through what to expect.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "title": "Consent & Termination of Parental Rights",
              "body": "Before finalization, the birth parent(s)' rights must be addressed — either through voluntary consent or court-ordered termination. We handle all aspects of this legally sensitive step, ensuring every document is executed correctly and that due process is followed.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "title": "Court Hearing",
              "body": "Alabama adoption finalization requires a court hearing before a judge. We attend with you, present the case, and answer any questions the judge may have. These hearings are typically brief and celebratory! Many clients bring family members and take photos in the courtroom.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "title": "Finalization & New Birth Certificate 🎉",
              "body": "The judge signs the Decree of Adoption — and your family is official! After finalization, we help you obtain a new birth certificate listing the adoptive parent(s) and, if applicable, apply for an updated Social Security record for the child.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            }
          ]
        },
        {
          "type": "faq",
          "label": "Legal Requirements",
          "background": "alt",
          "heading": "Alabama Adoption Requirements",
          "subtitle": "",
          "items": [
            {
              "q": "Residency Requirement",
              "a": "At least one party in the adoption must be a resident of Tennessee, or the child must have been in Tennessee for at least 6 months prior to filing.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "q": "Home Study Requirement",
              "a": "Required in most adoptions unless waived by the court (common in stepparent adoptions). Must be conducted by a licensed Tennessee adoption agency or social worker.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "q": "Background Check",
              "a": "All prospective adoptive parents must undergo state and federal criminal background checks. Certain prior convictions may disqualify a petitioner under Tennessee law.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "q": "Consent of the Child",
              "a": "If the child being adopted is 14 years of age or older, they must consent to the adoption in writing.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "q": "Waiting Period",
              "a": "For private placement and agency adoptions, a statutory waiting period applies before the final hearing. Stepparent adoptions generally have a shorter waiting period.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            }
          ]
        }
      ]
    },
    {
      "slug": "resource-guide",
      "navLabel": "Resource Guide",
      "emoji": "📄",
      "enabled": true,
      "sections": [
        {
          "type": "resources",
          "label": "Resources",
          "background": "alt",
          "heading": "Adoption Guides & Insights",
          "subtitle": "Plain-language resources to help you understand Alabama adoption law.",
          "items": [
            {
              "emoji": "📋",
              "tag": "Guide",
              "imagePath": "",
              "title": "Stepparent Adoption in Alabama: A Complete 2025 Guide",
              "excerpt": "Everything you need to know about legally adopting your stepchild in Alabama — requirements, timeline, costs, and common questions answered.",
              "date": "January 15, 2025",
              "readTime": "",
              "featured": "",
              "linkType": "none",
              "linkUrl": "home",
              "ctaLabel": ""
            },
            {
              "emoji": "⚖️",
              "tag": "Legal Info",
              "imagePath": "",
              "title": "What Is Termination of Parental Rights and When Is It Required?",
              "excerpt": "Before most adoptions can be finalized, a birth parent's rights must be legally terminated. Learn what that means and how it works in Alabama courts.",
              "date": "December 8, 2024",
              "readTime": "30 minute read",
              "featured": "",
              "linkType": "external",
              "linkUrl": "home",
              "ctaLabel": ""
            },
            {
              "emoji": "🌎",
              "tag": "Interstate",
              "imagePath": "",
              "title": "Navigating the ICPC: Interstate Adoption Explained",
              "excerpt": "If you're adopting a child from another state, you'll encounter the ICPC. Here's what it is, how it works, and how we help you through it.",
              "date": "November 22, 2024",
              "readTime": "5 min read",
              "featured": "",
              "linkType": "none",
              "linkUrl": "home",
              "ctaLabel": ""
            }
          ]
        }
      ]
    },
    {
      "slug": "faqs",
      "navLabel": "FAQs",
      "emoji": "📄",
      "enabled": true,
      "sections": [
        {
          "type": "faq",
          "label": "Common Questions",
          "background": "alt",
          "heading": "Frequently Asked Questions",
          "subtitle": "Everything you want to know about Alabama adoption law — answered plainly.",
          "items": [
            {
              "q": "How long does a stepparent adoption take in Tennessee?",
              "a": "Most uncontested stepparent adoptions in Tennessee take between 3 and 6 months from filing to finalization. The timeline depends on court availability, whether the other parent's rights need to be terminated, and how quickly the required documents are gathered.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "q": "Do I need a home study for a stepparent adoption?",
              "a": "Not always. Tennessee law allows the court to waive the home study requirement in stepparent adoptions when the petitioner has lived with the child for a sufficient period and the circumstances warrant it. We'll advise you based on your specific situation.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "q": "What if the birth parent won't consent to adoption?",
              "a": "If a birth parent refuses to consent, the court can still terminate their parental rights in certain circumstances — such as abandonment, failure to pay support, or unfitness. These are contested adoptions, which require a court hearing. We have extensive experience in contested adoption cases.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "q": "How much does adoption cost in Tennessee?",
              "a": "Costs vary significantly by adoption type. Stepparent and relative adoptions are typically the most affordable ($1,500–$4,000 in attorney fees). Private placement adoptions may involve additional costs including birth parent expenses, agency fees, and court costs. We provide transparent fee estimates in your consultation.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "q": "Can same-sex couples adopt in Tennessee?",
              "a": "Yes. Tennessee recognizes the right of same-sex couples to adopt. We proudly serve LGBTQ+ families in all types of adoption, including stepparent, second-parent, and agency adoptions.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "q": "What is the Interstate Compact on the Placement of Children (ICPC)?",
              "a": "The ICPC is a legal agreement between all U.S. states that governs how children can be placed for adoption across state lines. Before a child placed for adoption in one state can be brought to another state, both states must approve the placement. This adds time and paperwork — but we handle all of it.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "q": "Do I need an attorney for adoption in Tennessee?",
              "a": "Yes. Tennessee law requires that all adoptions be finalized in court, and you must have a licensed Tennessee attorney represent you. Attempting to complete an adoption without an attorney significantly increases the risk of errors that can delay or derail the process.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            },
            {
              "q": "What rights does an adopted child have?",
              "a": "An adopted child has the same legal rights as a biological child — including inheritance rights, the right to be covered by a parent's insurance, and access to Social Security benefits. The child will receive a new birth certificate listing the adoptive parent(s).",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            }
          ]
        }
      ]
    },
    {
      "slug": "unworthy",
      "navLabel": "Unworthy",
      "emoji": "📄",
      "enabled": true,
      "sections": [
        {
          "type": "testimonials",
          "label": "Hate Mail",
          "background": "alt",
          "heading": "Whining by the Outsiders",
          "subtitle": "Real stories from the unworthy that we find amusing.",
          "showReviews": false,
          "count": 3,
          "showReadAll": true,
          "readAllLabel": "Read All Reviews",
          "primarySource": true,
          "items": [
            {
              "name": "Frank Goodson",
              "initials": "FT",
              "stars": "1",
              "text": "I submitted a request for membership and now I'm subscribed to Women's World magazine and keep getting text messages from a doctors office asking me to confirm my appointment for a colonoscopy?!",
              "meta": "WTH • Richmond, VA"
            },
            {
              "name": "Tracy Billings",
              "initials": "TB",
              "stars": "1",
              "text": "Why did this page show up in my search for body piercings?",
              "meta": "Search Error • Grand Rapids, MI"
            },
            {
              "name": "Jim Friedman",
              "initials": "JF",
              "stars": "1",
              "text": "My employee keeps bossing me around and bosting about his OFL trophies and BRC records. I'd fire him for insubordination, but he's an incredible employee and the coolest guy I know. Because of your organization I feel so small.",
              "meta": "Unworthy • Southeastern US"
            }
          ]
        }
      ]
    },
    {
      "slug": "page-sections",
      "navLabel": "Page Sections",
      "emoji": "📄",
      "enabled": false,
      "sections": [
        {
          "type": "text",
          "label": "Text Block Section Label",
          "background": "alt",
          "heading": "Text Block Heading",
          "body": "Text Block Body Text - This is a generic page header with an optional body text field. Add this section first if adding sections that don't have page headers, like if creating a page with just a custom form, or a page of just links."
        },
        {
          "type": "two-col",
          "label": "Two Column Section Label",
          "background": "light",
          "heading": "Two Column Header",
          "body": "Two Column Body Text - When creating a new page, then add this section first, to create the page title with an optional body text, image, and button.",
          "imagePath": "images/hero-bkground-01.jpg",
          "imagePosition": "right",
          "cta_linkType": "external",
          "cta_linkUrl": "home",
          "cta_linkLabel": "Two Column Button Label"
        },
        {
          "type": "stats",
          "label": "Stats Bar Label",
          "background": "dark",
          "items": [
            {
              "num": "A1",
              "label": "Stats Bar 1"
            },
            {
              "num": "B2",
              "label": "Stats Bar 2"
            },
            {
              "num": "C3",
              "label": "Stats Bar 3"
            }
          ]
        },
        {
          "type": "feature-cards",
          "label": "Feature Cards Label",
          "background": "alt",
          "heading": "Feature Cards Heading",
          "body": "Feature Cards Body",
          "badgeNum": "10+",
          "badgeLabel": "Seasons",
          "items": [
            {
              "num": "01",
              "title": "Card 1 Title",
              "body": "Card 1 Description",
              "linkLabel": "Card 1 Link",
              "linkType": "external",
              "linkUrl": "home"
            },
            {
              "num": "02",
              "title": "Card 2 Title",
              "body": "Card 2 Description",
              "linkLabel": "Card 2 Link",
              "linkType": "file",
              "linkUrl": "home"
            },
            {
              "num": "03",
              "title": "Card 3 Title",
              "body": "Card 3 Description",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            }
          ]
        },
        {
          "type": "bullets",
          "label": "Bullet Section Label",
          "background": "light",
          "heading": "Bullet Section Header",
          "subtitle": "Bullet Section Subtitle",
          "items": [
            {
              "icon": "✓",
              "title": "Bullet Section Item 1",
              "desc": "Bullet Section Item 1 Description",
              "linkType": "external",
              "linkUrl": "home"
            },
            {
              "icon": "✓",
              "title": "Bullet Section Item 2",
              "desc": "Bullet Section Item 2 Description",
              "linkType": "file",
              "linkUrl": "home"
            }
          ]
        },
        {
          "type": "services",
          "label": "Services Grid Label",
          "background": "dark",
          "heading": "Services Grid Header",
          "subtitle": "Services Grid Subtitle",
          "items": [
            {
              "icon": "⚖️",
              "title": "Services Grid Service 1 Title",
              "desc": "Services Grid Service 1 Description",
              "detail": "Services Grid Service 1 Detail Modal Popup",
              "btnLabel": "Services 1 Modal Button",
              "btnLinkType": "external",
              "btnLinkUrl": "home"
            },
            {
              "icon": "⚖️",
              "title": "Services Grid Service 2 Title",
              "desc": "Services Grid Service 2 Description",
              "detail": "Services Grid Service 2 Detail Modal Popup",
              "btnLabel": "Services 2 Modal Button",
              "btnLinkType": "file",
              "btnLinkUrl": "home"
            },
            {
              "icon": "⚖️",
              "title": "Services Grid Service 3 Title",
              "desc": "Services Grid Service 3 Description",
              "detail": "Services Grid Service 3 Detail Modal Popup",
              "btnLabel": "",
              "btnLinkType": "none",
              "btnLinkUrl": "home"
            }
          ]
        },
        {
          "type": "steps",
          "label": "Process Steps Label",
          "background": "dark",
          "heading": "Process Steps Heading",
          "subtitle": "Process Steps Subtitle",
          "items": [
            {
              "title": "Process Steps 1 Title",
              "body": "Process Steps 1 Description",
              "linkLabel": "Step 1 Button Label",
              "linkType": "external",
              "linkUrl": "home"
            },
            {
              "title": "Process Steps 2 Title",
              "body": "Process Steps 2 Description",
              "linkLabel": "Step 2 Button Label",
              "linkType": "file",
              "linkUrl": "home"
            }
          ]
        },
        {
          "type": "faq",
          "label": "FAQ Section Label",
          "background": "light",
          "heading": "FAQ Section Heading",
          "subtitle": "FAQ Section Subtitle",
          "items": [
            {
              "q": "FAQ Section Q1",
              "a": "FAQ Section Q1 Answer",
              "linkLabel": "FAQ 1 Link Label",
              "linkType": "external",
              "linkUrl": "home"
            },
            {
              "q": "FAQ Section Q2",
              "a": "FAQ Section Q2 Answer",
              "linkLabel": "FAQ 2 Link Label",
              "linkType": "file",
              "linkUrl": "home"
            }
          ]
        },
        {
          "type": "checklist",
          "label": "Document Label",
          "background": "light",
          "heading": "Document Heading",
          "subtitle": "Document Subtitle",
          "categories": [
            {
              "title": "Document Category 1 Title",
              "items": [
                "Document Category 1 a",
                "Document Category 1 b",
                "Document Category 1 c",
                "Document Category 1 d"
              ]
            },
            {
              "title": "Document Category 2",
              "items": [
                "Document Category 2 a",
                "Document Category 2 b",
                "Document Category 2 c",
                "Document Category 2 d"
              ]
            }
          ]
        },
        {
          "type": "timeline",
          "label": "Timeline Label",
          "background": "dark",
          "heading": "Timeline Heading",
          "subtitle": "Timeline Subtitle",
          "items": [
            {
              "date": "Timeline Event 1 Date/Phase",
              "title": "Timeline Event 1 Title",
              "body": "Timeline Event 1 Description",
              "linkLabel": "Event 1 Link",
              "linkType": "external",
              "linkUrl": "home"
            },
            {
              "date": "Timeline Event 2 Date/Phase",
              "title": "Timeline Event 2 Title",
              "body": "Timeline Event 2 Description",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            }
          ]
        },
        {
          "type": "fees",
          "label": "Fee Schedule Label",
          "background": "dark",
          "heading": "Fee Schedule Heading",
          "subtitle": "Fee Schedule Subtitle",
          "disclaimer": "",
          "items": [
            {
              "service": "Fee Schedule Service 1",
              "amount": "Fee 1",
              "detail": "Fee Schedule Service 1 Details",
              "note": "Fee Schedule Service 1 Note",
              "linkLabel": "Fee 1 Link",
              "linkType": "external",
              "linkUrl": "home"
            },
            {
              "service": "Fee Schedule Service 2",
              "amount": "Fee 2",
              "detail": "Fee Schedule Service 2 Details",
              "note": "Fee Schedule Service 2 Note",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home"
            }
          ]
        },
        {
          "type": "jurisdiction",
          "label": "Jurisdiction Label",
          "background": "alt",
          "icon": "⚖️",
          "title": "Jurisdiction Title",
          "heading": "Jurisdiction Heading",
          "body": "Jurisdiction Body",
          "linkLabel": "Jurisdiction Link",
          "linkType": "external",
          "linkUrl": "home"
        },
        {
          "type": "team",
          "label": "Team Label",
          "background": "dark",
          "heading": "Team Heading",
          "useAttorneys": true
        },
        {
          "type": "testimonials",
          "label": "Testimonial Label",
          "background": "alt",
          "heading": "Testimonial Heading",
          "subtitle": "Testimonial Subtitle",
          "showReviews": true,
          "count": 3,
          "showReadAll": true,
          "readAllLabel": "Read All Reviews",
          "primarySource": false,
          "items": []
        },
        {
          "type": "form",
          "label": "Custom Form Label",
          "background": "dark",
          "heading": "Custom Form Heading",
          "intro": "Custom Form Intro (optional)",
          "submitLabel": "Send Message",
          "successMsg": "Thank you! We'll be in touch soon.",
          "endpoint": "",
          "fields": [
            {
              "type": "text",
              "label": "Text Field Label",
              "placeholder": "Text Field Placeholder",
              "required": true,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "textarea",
              "label": "Textarea",
              "placeholder": "Textarea Placeholder",
              "required": true,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "select",
              "label": "Select Label",
              "placeholder": "Select Placeholder",
              "required": true,
              "halfWidth": false,
              "options": [
                "Select 1",
                "Select 2",
                "Select 3"
              ]
            },
            {
              "type": "radio",
              "label": "Radio Label",
              "placeholder": "Radio Placeholder",
              "required": true,
              "halfWidth": false,
              "options": [
                "Radio 1",
                "Radio 2",
                "Radio 3"
              ]
            },
            {
              "type": "checkbox",
              "label": "Checkbox Label",
              "placeholder": "Checkbox Placeholder",
              "required": true,
              "halfWidth": false,
              "options": []
            }
          ]
        },
        {
          "type": "link",
          "label": "",
          "background": "light",
          "linkType": "internal",
          "linkLabel": "Link Label",
          "linkUrl": "home"
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "primary_linkType": "internal",
          "primary_linkLabel": "Button Label",
          "primary_linkUrl": "home",
          "secondary_linkType": "internal",
          "secondary_linkLabel": "Secondary Button Label",
          "secondary_linkUrl": "home"
        }
      ]
    }
  ],
  "heroPrimaryDest": "contact",
  "heroSecondaryDest": "services",
  "homeSections": [
    {
      "type": "feature-cards",
      "label": "Why Choose Us...",
      "background": "light",
      "heading": "You Don't...You are Chosen!",
      "body": "Being a part of this organization isn't even a birth right. Here, blood only means something when its spilled fighting for championship glory.",
      "badgeNum": "30+",
      "badgeLabel": "Champions",
      "items": [
        {
          "num": "BRC",
          "title": "Blue Ribbon Cup",
          "body": "Think you know how to negotiate a 64 lane highway with four bald 12 seeds strapped to your rig. You don't and you'll find out soon enough, no else does either.",
          "linkLabel": "Road to the BRC",
          "linkType": "external",
          "linkUrl": "https://auspider98.github.io/OFL/league.html?league=brc"
        },
        {
          "num": "OFC",
          "title": "Osborne Football Club",
          "body": "An exclusive club for those who think they can ride a roster full of overpaid talent to the height of monstrous glory.",
          "linkLabel": "Gridiron Battlefield",
          "linkType": "external",
          "linkUrl": "https://auspider98.github.io/OFL/league.html?league=ofc"
        }
      ]
    },
    {
      "type": "testimonials",
      "label": "Hate Mail",
      "background": "alt",
      "heading": "Whining by the Outsiders",
      "subtitle": "Real stories from the unworthy that we find amusing.",
      "items": [],
      "showReviews": true,
      "count": 3,
      "showReadAll": true,
      "readAllLabel": "Read All Reviews",
      "primarySource": false
    }
  ],
  "footerBio": "Where Legends Are Made & Legacies Are Settled",
  "aboutBio3": "She is a member of the Alabama Bar Association, the American Academy of Adoption Attorneys (AAAA), and has been recognized as a Super Lawyer in Alabama Family Law for eight consecutive years. She is admitted to practice in all Alabama courts and regularly handles cases in Jefferson, Shelby, St. Clair, and Cullman counties.",
  "aboutBio4": "When she's not advocating for families in court, Amy volunteers with the Alabama Foster Care Association and speaks at community workshops on adoption awareness.",
  "_savedAt": 1775851365469,
  "contactSubmitLabel": "Request Free Abuse",
  "contactSuccessMsg": "Ugh...you're so unworthy."
};
